### ISSUE TITLE
unbound unable to start

### ISSUE THREAD

**Issue by SIMONTEHGEEK** [bntjah/lancache#85]
Ran the installer script from latest gitpull - restart the server and unbound is unable to start:

Feb 27 14:56:52 CACHE-SERVER package-helper[7387]: /etc/unbound/unbound.conf:2: error: syntax error
Feb 27 14:56:52 CACHE-SERVER package-helper[7387]: read /etc/unbound/unbound.conf failed: 1 errors in configuration file
Feb 27 14:56:52 CACHE-SERVER package-helper[7398]: /etc/unbound/unbound.conf:2: error: syntax error
Feb 27 14:56:52 CACHE-SERVER package-helper[7398]: read /etc/unbound/unbound.conf failed: 1 errors in configuration file
Feb 27 14:56:52 CACHE-SERVER unbound[7401]: /etc/unbound/unbound.conf:2: error: syntax error
Feb 27 14:56:52 CACHE-SERVER unbound[7401]: read /etc/unbound/unbound.conf failed: 1 errors in configuration file
Feb 27 14:56:52 CACHE-SERVER unbound[7401]: [1519743412] unbound[7401:0] fatal error: Could not read config file: /etc/unbound/unbound.conf
Feb 27 14:56:52 CACHE-SERVER systemd[1]: unbound.service: Main process exited, code=exited, status=1/FAILURE
Feb 27 14:56:52 CACHE-SERVER systemd[1]: Failed to start Unbound DNS server.

I haven't changed anything, this is a fresh install, running on a VM of Ubuntu Server (17) with a single ethernet as a bridge (the VM has it's only IP taken from my routers DHCP) 10.0.0.17

Any help would be great! thank you. :)

**Comment by SIMONTEHGEEK** [comment]
Here is a copy of my host file from /etc/host

 

127.0.0.1       localhost
127.0.1.1       CACHE-SERVER

# The following lines are desirable for IPv6 capable hosts
# ::1     localhost ip6-localhost ip6-loopback
# ff02::1 ip6-allnodes
# ff02::2 ip6-allrouters

127.1.0.1       lancache-origin-backend
127.1.0.2       lancache-blizzard-backend

#This is the primary IP (of the network card / eth) that your Lancache is using
 lancache-eth

#The Following are Virtual IP's used by Lancache
...1 lancache-steam
...2 lancache-riot
...3 lancache-blizzard
...4 lancache-hirez
...5 lancache-origin
...6 lancache-sony
...7 lancache-microsoft
...8 lancache-enmasse
...9 lancache-gog
...10 lancache-arenanetworks
... lancache-apple
...11 lancache-wargaming
... lancache-uplay
... lancache-glyph
 lancache-zenimax
 lancache-digitalextremes
lc-host-perlabyss lancache-pearlabyss

**Comment by SIMONTEHGEEK** [comment]
and of /etc/unbound/unbound.conf

```
#server:
    verbosity: 1
    statistics-interval: 10
     num-threads: 1
     interface:
     cache-min-ttl: 60
     cache-max-ttl: 86400
     do-daemonize: yes
     do-ip6: no
     access-control: 0.0.0.0/0 allow
     log-queries: no
     hide-version: yes
     identity: "lancache DNS"
     harden-short-bufsize: no
     harden-large-queries: no
     harden-glue: yes
     rrset-cache-size: 256m
     msg-cache-size: 128m


    ## LANcache config ##

    ## Steam °|-lc-host-vint:1
        local-zone: "steampowered.com." transparent
        local-zone: "client-download.steampowered.com." redirect
        local-data: "client-download.steampowered.com. 600 IN A ...1"
        local-zone: "content1.steampowered.com." redirect
        local-data: "content1.steampowered.com. 600 IN A ...1"
        local-zone: "content2.steampowered.com." redirect
        local-data: "content2.steampowered.com. 600 IN A ...1"
        local-zone: "content3.steampowered.com." redirect
        local-data: "content3.steampowered.com. 600 IN A ...1"
        local-zone: "content4.steampowered.com." redirect
        local-data: "content4.steampowered.com. 600 IN A ...1"
        local-zone: "content5.steampowered.com." redirect
        local-data: "content5.steampowered.com. 600 IN A ...1"
        local-zone: "content6.steampowered.com." redirect
        local-data: "content6.steampowered.com. 600 IN A ...1"
        local-zone: "content7.steampowered.com." redirect
        local-data: "content7.steampowered.com. 600 IN A ...1"
        local-zone: "content8.steampowered.com." redirect
        local-data: "content8.steampowered.com. 600 IN A ...1"
        local-zone: "cs.steampowered.com." redirect
        local-data: "cs.steampowered.com. 600 IN A ...1"
        local-zone: "clientconfig.akamai.steamtransparent.com." redirect
        local-data: "clientconfig.akamai.steamtransparent.com. 600 IN A ...1"
        local-zone: "hsar.steampowered.com.edgesuite.net." redirect
        local-data: "hsar.steampowered.com.edgesuite.net. 600 IN A ...1"
        local-zone: "steamcontent.com." redirect
        # local-data: "steampipe.steamcontent.com. 600 IN A ...1"
        local-data: "steamcontent.com. 600 IN A ...1"
        local-zone: "edgecast.steamstatic.com." redirect
        local-data: "edgecast.steamstatic.com. 600 IN A ...1"
        local-zone: "steampipe.akamaized.net." redirect
        local-data: "steampipe.akamaized.net. 600 IN A ...1"
        local-zone: "steam.apac.qtlglb.com." redirect
        local-data: "steam.apac.qtlglb.com. 600 IN A ...1"
        local-zone: "steam.apac.qtlglb.com.mwcloudcdn.com." redirect
        local-data: "steam.apac.qtlglb.com.mwcloudcdn.com. 600 IN A ...1"
```
